
# Enable specific cells by label. Leave empty or comment out to enable all registered cells.
enabled_cells:
  - PV_reduced
  - SOM_reduced
  - VIP_reduced
  - NGF_reduced
  - IT5A_full
  - PT5B_full
  - IT2_reduced
  - IT4_reduced
  - IT5A_reduced
  - IT5B_reduced
  - PT5B_reduced
  - IT6_reduced
  - CT6_reduced
