cfg_defaults:
  diversity: true
  percentage: 0.05

  dt: 0.025
  seeds:
    conn: 4321
    stim: 1234
    loc: 4321
    tvl_sampling: 1234
    cell: 1234
    m1_sampling: 1234
  hParams:
    celsius: 34
    v_init: -80

  verbose: false
  createNEURONObj: true
  createPyStruct: true
  connRandomSecFromList: false
  cvode_active: false
  cvode_atol: 1.0e-6
  cache_efficient: true
  printRunTime: 0.1
  printSynsAfterRule: false
  pt3dRelativeToCellLocation: true
  oneSynPerNetcon: true
  validateNetParams: true
  progressBar: 0

  includeParamsLabel: false
  checkErrors: false
  checkErrorsVerbose: false
  rand123GlobalIndex: null
  coreneuron: true
  random123: true
  gpu: false

  recordStim: false
  recordTime: false
  transient: 0
  UMAP_params: {}
  n_components: 2
  sampled_cells: {}
  savePickle: false
  saveJson: false
  saveDataInclude: [simData, simConfig, netParams]
  backupCfgFile: null
  gatherOnlySimData: false
  saveCellSecs: false
  saveCellConns: 0
  compactConnFormat: 0

  recordTraces:
    V_soma: {sec: soma, loc: 0.5, var: v}
    V_apic_3: {sec: apic_3, loc: 0.5, var: v, conds: {pop: PT5B}}
    V_dend_1: {sec: dend_1, loc: 0.5, var: v, conds: {pop: PT5B}}

  cao_secs: 1.2
  loadmutantParams: false
  variant: WT

  KCNT1: false
  mutations_enabled: false
  mutations_dry_run: false

  verbose_drug_changes: false
  drug_dry_run: false
  cell_drugs:
    - {cell_types: [PV, SOM], mech: nax, param: gbar, op: set, value: 0.0, sections: ALL}
    - {cell_types: [PT, IT], mech: nax, param: gbar, op: set, value: 0.0, sections: ALL}
    - {cell_types: [PT, IT], mech: na12, param: gbar, op: set, value: 0.0, sections: ALL}
    - {cell_types: [PT, IT], mech: na12mut, param: gbar, op: set, value: 0.0, sections: ALL}
    - {cell_types: [VIP], mech: Ih, param: gIhbar, op: scale, value: 0.2, sections: ALL}
    - {cell_types: [NGF], mech: hd, param: gbar, op: scale, value: 1.5, sections: [dend]}
    - {cell_types: [SOM], mech: catcb, param: gcatbar, op: scale, value: 0.5, sections: [soma]}
  syn_drugs:
    - {syn_mechs: [NMDA], param: tau2NMDA, op: scale, value: 0.5}
    - {syn_mechs: [AMPA], param: tau2, op: scale, value: 0.8}
    - {syn_mechs: [GABAA, GABAA_VIP], param: e, op: set, value: -70}
    - {syn_mechs: [GABAB], param: tau2, op: scale, value: 1.25}

  cellmod:
    IT2: HH_reduced
    IT4: HH_reduced
    IT5A: HH_full
    IT5B: HH_reduced
    PT5B: HH_full
    IT6: HH_reduced
    CT6: HH_reduced

  ihModel: migliore
  ihGbarZD: null
  ihGbarBasal: 1.0
  ihlkc: 0.2
  ihlkcBasal: 1.0
  ihlkcBelowSoma: 0.01
  ihlke: -86
  ihSlope: 28

  somaNa: 5
  axonNa: 7
  axonRa: 0.005
  gpas: 0.5
  epas: 0.9

  synWeightFractionEE: [0.5, 0.5]
  synWeightFractionEI: [0.5, 0.5]
  synWeightFractionSOME: [0.9, 0.1]
  synWeightFractionNGF: [0.5, 0.5]

  synsperconn:
    HH_full: 5
    HH_reduced: 1
    HH_simple: 1
  AMPATau2Factor: 1.0

  addSynMechs: true
  distributeSynsUniformly: true

  layer:
    '1': [0.0, 0.1]
    '2': [0.1, 0.29]
    '4': [0.29, 0.37]
    '5A': [0.37, 0.47]
    '24': [0.1, 0.37]
    '5B': [0.47, 0.8]
    '6': [0.8, 1.0]
    longTPO: [2.0, 2.1]
    longTVL: [2.1, 2.2]
    longS1: [2.2, 2.3]
    longS2: [2.3, 2.4]
    longcM1: [2.4, 2.5]
    longM2: [2.5, 2.6]
    longOC: [2.6, 2.7]

  singleCellPops: false
  weightNorm: 1
  weightNormThreshold: 4.0

  allowConnsWithWeight0: true
  allowSelfConns: false
  scale: 1.0
  sizeY: 1350.0
  sizeX: 300.0
  sizeZ: 300.0
  correctBorderThreshold: 150.0

  L5BrecurrentFactor: 1.0
  ITinterFactor: 1.0
  strengthFactor: 1.0

  IEdisynapticBias: null
  EPVGain: 1.0
  ESOMGain: 1.0
  PVEGain: 1.0
  SOMEGain: 1.0
  PVSOMGain: null
  SOMPVGain: null
  PVPVGain: null
  SOMSOMGain: null
  IPTGain: 1.0
  IFullGain: 1.0

  noiseLong: 1.0
  delayLong: 5.0
  startLong: 0
  numSampledCellsPerLayer: null

  pulse:
    pop: None
    start: 1000
    end: 1100
    rate: 20
    noise: 0.8
  pulse2:
    pop: None
    start: 1000
    end: 1200
    rate: 20
    noise: 0.5
    duration: null

  IClamp1:
    pop: IT5B
    sec: soma
    loc: 0.5
    start: 0
    dur: 1000
    amp: 0.5

  NetStim1:
    pop: IT2
    ynorm: [0, 1]
    sec: soma
    loc: 0.5
    synMech: [AMPA]
    synMechWeightFactor: [1.0]
    start: 500
    interval: 16.666666666666668
    noise: 0.0
    number: 60.0
    weight: 30.0
    delay: 0

allpops:
  - NGF1
  - IT2
  - PV2
  - SOM2
  - VIP2
  - NGF2
  - IT4
  - PV4
  - SOM4
  - VIP4
  - NGF4
  - IT5A
  - PV5A
  - SOM5A
  - VIP5A
  - NGF5A
  - IT5B
  - PT5B
  - PV5B
  - SOM5B
  - VIP5B
  - NGF5B
  - IT6
  - CT6
  - PV6
  - SOM6
  - VIP6
  - NGF6

recpops: [PV2, PV4, PV5A, PV5B, PV6, PT5B]

long_rate_templates:
  LongRangeQuiet: [0, 2.5]
  TVLquiet: [0, 2.5]
  TVLmovement: [0, 10]
  ihQuiet: 1.0
  ihMovement: 0.25
